### ISSUE TITLE
now the PolyGnome

### ISSUE THREAD

**Issue by alto777** [baconpaul/BaconPlugs#10]
hi Paul and thank you for your patience and generosity.

I looked into the heart of the PolyGnome clock generator because I was musing about the possibilities of a clock multiplier.

If you could confirm: you run one real clock in the tradition phase accumulation method, maintained with a longer time base than one cycle. Then you calculate fractional products of this one phase for the four other clocks.

If I set up 5/7 and 7/5, and the internal unity clock is 1/1 =, say, 1 Hz, then I will get 50% duty cycle square wave outputs at 0.7143 and 1.4 Hz. The math guarantees that every 35 cycles the edges of the two derived clocks are coincident.

And even though the product of all denominators and numerators is large, it fits in 64 bits, so no trouble there.

After trying to think of a way around the huge product - even going to the trouble of eliminating common factors is NG as you must account for edge cases - I wrote a distinctly different heart in a copy of PolyGnome except the clock logic. It works except I do not able to guarantee synchronous edges. No dount an approach you tried or realized before going to the trouble wouldn't work, or would be kludgy to fix. but it was fun anyway. After I got all the + 1s in the right places. ;-)

		float clockTime = powf(2.0f, params[CLOCK_PARAM].value + inputs[CLOCK_INPUT].value);
	
	/* compute 4 additional phase addends */

		float unitPhase = clockTime * engineGetSampleTime();
		float phaseAddend[NUM_CLOCKS + 1];
		phaseAddend[0] = unitPhase;
		for (int i = 0; i < NUM_CLOCKS; i++)
			phaseAddend[i + 1] = (unitPhase * deni(i)) / numi(i); 
		
	/* accumulate all phases, reduce and form output */

		for (int i = 0; i < NUM_CLOCKS + 1; i++) {
			nPhases[i] += phaseAddend[i];
			while (nPhases[i] >= 1.0f)
				nPhases[i] -= 1.0f;
			outputs[CLOCK_GATE_0 + i].value = (nPhases[i] < 0.5f) ? 10.0f : 0.0f;
		}

 

a7

**Comment by baconpaul** [comment]
If you go back isn’t the revision history on PolyGnome you’ll see I started with code which looks quite a lot like this, but ended up with the various convolutions so that, yes, the clocks had a starting crossing point which didn’t drift.

https://github.com/baconpaul/BaconPlugs/commit/e3e61d0abcf45fc913da5a0a28198dc46f928cab#diff-4f8ea5ce38371f0889932a0bbd3b14d6

Is a useful diff and here’s a version 0.1 of the code which looks quite a lot like your code

https://github.com/baconpaul/BaconPlugs/commit/c61c15d3296883ff3c55136b4ddf9ff841c5991a#diff-4f8ea5ce38371f0889932a0bbd3b14d6

Just arranged a bit differently.

But what i really wanted was if you change from 1/3 to 1/4 and back to 1/3, when you are back to 1/3, one out of every three clocks is contemporaneous without overflowing. For that you need to track a global max clock which is how I got the somewhere more convoluted core I ended up with.

Of course, since the stepper is not factored out for an independent test I can’t prove this in a unit test. That’s one of those things I’ll do in 0.6.3 this summer.

**Comment by alto777** [comment]
Thanks, I will take a look. I am intrigued by your approach for testing which seems to avoid the various problems (cough) that occur when primitive cut and paste and try to make the same algo run elsewhere work the same.

a7

**Comment by baconpaul** [comment]
Yeah take a look at the diff I just pushed for #16 which shows how I'm starting to do it, including having the Glissinator and SampleDelay tests be assertive with no rack to test my stepper, and #11 which is starting to apply same to PolyGnome so these statements I make here can become assertive test cases.
