### ISSUE TITLE
Implement the more generic LFSR random noise

### ISSUE THREAD

**Issue by baconpaul** [baconpaul/BaconPlugs#15]
Features include

- bit sizes from 8 to 24
- active bits for feedback filters controlled by lights
- ability to set lights to optimal long sequences as on the wiki
- ability to seed with a float

To do this we will probably need #13 done for the lights and #14 for the hex display.

**Comment by alto777** [comment]
This will be nice. LSFRs are good for more than noise. Dunno if any of this would fit in your concept:

A. have a gate ouput on each lamp w/ duty cycle equal to input clock
B. select Fibonacci or Galois feedback method
B.5 choice of no all 1s or all 0s illegal state? In one of the two feedback methods I think this is just choosing XNOR insteasd of XOR. Not sure about the other, or which is which obv.
C. preset/set by clicking on state lamps any

D. I don't think is possible, really, if it had to be done in a step's time, but it would be nice to see the length that the current parameters result in. Since it can be a large number and I have not come across a way to compute this other than by exhaustion.

My next LFSR thing is lagging behind other experiments and such time as I manage to spend _not_ playing with Rack and Rack coding!

a7

**Comment by baconpaul** [comment]
yeah your C is my third bullet. I think D is probably 'hard' but not impossible. Just show how long it was until you revisit your seed. Keep it as a counter. B is easy enough to do and a good idea.

Not sure I get A. What exactly do you mean?

This is more a "summer project" than a "now project" for me, just so you know.

**Comment by baconpaul** [comment]
So on "D" I think what I will do is figure out the length of the sequence by observation. So start a counter at seed. Reset it if any params change. When I revisit seed show the length of the counter (and have it be -1 any other time). That way if you let it run for a long time you will eventually see the signal.

I can also have a "pre-calculate" which does the calculation on a separate thread outside of the step mechanism. Just spin up a thread and burn CPU until you loop and set that number. May consider adding that. Not sure. I will write my oscillator so we can do that, though.

**Comment by alto777** [comment]
Ok, IC. 

- bits for feedback filters controlled by lights
- ability to set lights to optimal long sequences as on the wiki

The first means picking which bits are tapped. The second refers to setting/clearing any of the N bits in the shift register, yes my item C.

Somehow I thought you meant having a table of preset taps, 1 or more for each shift register length, that would produce maximal length sequences. And some means to inject that into the tap set instead of toggling the bits to be tapped on/off manually. I came across an example like this that used a menu, all were 4-taps for a 16 bit shift register, just 4 digit hex numbers right there on a pop=up. There are quite a few as you may know. There is a website listing taps sets: https://users.ece.cmu.edu/~koopman/lfsr/index.html.

In A, I meant that each shift register bit would have a lamp showing its current state and an output that would be high if the lamp was on (bit set) while the clock was also high. I appreciate that it would be a slew of outputs. I've thought about other ways to break out shift register stages, like having a small number avaible, say four, and some means of specifying which bit each of the four was following, much like the tapping logic itself.

But it's your trip, natch. As I said, I may live long enough to make another LFSR/counter thing myself. I feel like thelonger I wait the better it will be, still learning about what I want and how to do some things. On the other hand, waiting until something isperfect means never it sees the light of day…

a7

**Comment by baconpaul** [comment]
I did mean a table of preset taps! But those just light up lights which you can then edit. Basically the taps are up-to 24 buttons if I do up-to 24 bits. But you are right that there’s which taps and which value. I want to control both but having a good preset for both as a function of n matters.

I see what you’re saying in a. Basically you can output a single bit other than bit 0. Isn’t that just a time delayed output though? Namely if you track bit 4 say that’s just a four shift delay on bit 0? But it’s an easy feature to add. I think the ux you suggest of dial-a-bit-to-pick makes sense

Thanks!

**Comment by alto777** [comment]
Apply "It is my understanding" as a general caveat!

Both Fibonacci and Galois style LFSR feedback arrangements generate identical bit-out patterns with equal tap words. The Galois algo is a bit simpler to implement. For noise, it makes no difference, so.

In the case of Fibonacci, you observe correctly that it's just time delay. But in Galois, the tap word is broadside XORed into the register, so a bit pattern does not merely make its way down the register unmoleseted so to speak. The bits falling out form the same sequence, but the internal states do not track. both algos hit all the legal states, just not in the same order.

But in either case one (me) wants to have access to every bit. It is in selecting and weighting the bits that interesting (or not) sequences of numbers -> CVs can be produced. The Stellare Turing Machine plug shows this sorta, as do my own Rack plugins more explicitly.

This is also why I was looking at quantization. I use the binary-weighted bits to form a number which is more like a MIDI note number than a control voltage. So my "quantization" was and remains keeping the number internally, but using a # -> CV informed by a (selectable) scale to output a traditional CV. So far I've only used 2 - major and chromatic. I plan to make it easy to use any scale, perhaps with a nifty "pick the notes" interface like your QuantEyes with the addition of a pick-the-scale to start with knob*. Or maybe even go off the res a bit and allow pciking n number of pitches not necesarily aligned with Western constraints. I did find a quantizer that was trainable in that manner: http://www.bartonmusicalcircuits.com/uwq/ 

*which would fit, BTW, on your Quantizer if the horizontal bars were all short  you could have a scale select knob. See JW-Modules Quantizer, very straight ahead. 

But thinking this stuff up is so much faster than doing it… even in software.

a7

**Comment by baconpaul** [comment]
You are making me think I may write two uis with the same core stepper... I get it, sort of an lsfr for noise and an lsfr for other-stuff and the other stuff one has a ui which exposes every bit, let’s you explicitly step with a trigger and what not, where as the noise one has a frequency which drives steps and only outputs the output bit. That’s super easy to do with the templates stepper approach I’ve been taking. Good idea.

Again this is a summer not a now project for me.  

On quanteyes I thought about enumerating every scale ever but decided to make a piano keyboard approach with buttons instead. Now I have the dial a text widget thing which I use in ks I suppose I could do two quanteyes uis also using the same core. I’ll ponder that one some before I do anything though.
