### ISSUE TITLE
notes on latest build

### ISSUE THREAD

**Issue by davephillips** [baconpaul/BaconPlugs#2]
Linux Fedora 23
Rack 0.5.x

Clean build, no problems. Plugins load fine without GUI issues and all perform well. Just thought you'd like to know. :) Well done, sir !

**Comment by baconpaul** [comment]
Excellent. Thanks! I'll get together a binary release and push to the community list by mid-week. Appreciate your testing. Enjoy the plugs!

**Comment by baconpaul** [comment]
Well it's still 13 degrees out where I am, so put together binary builds in my vm and my mac now, made a GH release, and updated the community. 

https://github.com/VCVRack/community/pull/161

if/when they merge this PR, I should be released. I thanked you specifically in the 0.5.0 release notes. Appreciate your help. Thanks!

**Comment by baconpaul** [comment]
Oh @davephillips so Andrew suggested I use a different slug name (Bacon Music rather than BaconPlugs) which I think is a good idea. So I'm making that change.

It means if you are building any patches, when I do the push and release they won't work any more since the Slug Name is stored as text in the .vcv file.

    sed -i .bak -e 's/BaconPlugs/Bacon Music/' *.vcv

will be the thing you need. Probably doing that with release in the next few days. Don't know if you are using the build in anything at all, but wanted to share this so you know it's coming down the pipe!
