### ISSUE TITLE
add header to Phaser.hpp

### ISSUE THREAD

**Issue by davephillips** [baconpaul/BaconPlugs#22]
Fedora 23 Linux
GCC 5.3.1
Rack v1.dev.7bde284

Hi Paul, thanks for the note on the community forum. I built your plugin today with the latest v1 pull, ran into one problem. Phaser.cpp threw an error about size_t undefined in the scope - probably due to my old compiler - that I resolved by adding `#include <cstddef>` to Phaser.hpp. Otherwise, no errors, your modules appear as expected in the Browser, and they all instantiate without problems. I'll test as many as I can and will let you know if I run into any anomalous behavior. :)

**Comment by baconpaul** [comment]
Hey thanks. Since there's no rack SDK for 1.0 my CI builds don't actually work so I hadn't even tried Windows or Linux with my port I just realized!  Appreciate the report and I just pushed a rev to the candidate 1.0 branch with your fix (associated above with this issue).

I'll close this issue and appreciate any tests or feedback you may have!
