### ISSUE TITLE
KarplusStrongPoly trigger max trigger states is 10

### ISSUE THREAD

**Issue by Coirt** [baconpaul/BaconPlugs#28]
https://github.com/baconpaul/BaconPlugs/blob/master/src/KarplusStrongPoly.cpp#L63

Just had a quick look there, The trigger states and the output button have 11 states. So it makes triggering manually near impossible, not sure what the output button button is doing.

Also the poly output depends on an incoming poly trigger but if trigger is not connected the output is poly. It only gets 1 channel when you manually hit the trigger. 

https://github.com/baconpaul/BaconPlugs/blob/master/src/KarplusStrongPoly.cpp#L131
```
int nChan;
        if( inputs[TRIGGER_GATE].isConnected() )
            nChan = std::max(1,inputs[TRIGGER_GATE].getChannels());
        else
            nChan = 16;
```
Perhaps:
```
int nChan;
        if(!inputs[TRIGGER_GATE].isConnected() )
            int nChan = 1;
        else
            nChan = std::max(1,inputs[TRIGGER_GATE].getChannels());
//not sure std max is needed here as the max is always 1 or number of channels connected 
```

**Comment by baconpaul** [comment]
So the reason I made this choice is because of what happens when you disconnect a polyphonic trigger. I could have made a different choice but here's the scenario

Hook up a poly gate to KS poly. That starts sending notes down a polyphonic output.

If you unhook that polyphonic trigger and collapse back to one channel, there are still voices running which want to output.

So I have three choices

1. Collapse those voices to a single poly channel when you unhook the gate. That would be the output summing code below being aware of maxChan and pushing onto chan 0 if it got a residual voice
2. Make sure the output is 16 wide if I don't know how big to make it. That's what the code here does
3. Make nChan == highest chan of a playing voice if no input is connected. That's a better idea

But your change will cause a crash if you unhook a poly gate - which is why that if is in there actually! (Because I originally had exactly your code and it crashed when I uncooked a poly gate :) )

You are correct my approach has the weird choice of press the button and always get 16 channel polyphony. So maybe choice 3 is a better choice. I think moving voices from one channel to another because you unhook a gate, or killing voices because you unhook a gate, is undesirable though, yeah?

But this one is tricky. Not obvious what to do!

**Comment by baconpaul** [comment]
Also what does "trigger manually near impossible" mean? And the output button kills all voices.

**Comment by baconpaul** [comment]
(but the UI makes that very unclear I agree; I want to modify this panel at some point).

**Comment by Coirt** [comment]
Okay fair enough.

I mean by near impossible.....
![buttonState](https://user-images.githubusercontent.com/12150421/59147346-16419b00-89f2-11e9-80a8-ba5b520b158b.gif)

Triggers only on 0 so kill only happens on 0 also

**Comment by baconpaul** [comment]
Ahh yeah that trigger button is decidedly not very useful I agree. Let me check the kill thing. Hold on.

**Comment by baconpaul** [comment]
Ahh I see the button problem. They are not properly momentary (although they do kill the signal properly if you transition them from 0 to 1). That's a real bug! I'll take a look.

**Comment by baconpaul** [comment]
So if you RM and set a value to 0 then enter, then RMB and set it to 1 it works.
Clicking the button no longer does that though.

**Comment by baconpaul** [comment]
Yeah OK so the switch API in v1.0 changed and I didn't use it properly on that button (I got most others). Can you pull the latest master or release_v1.0.1 and then that button should indeed silence all channels gracefully.

**Comment by baconpaul** [comment]
And the trigger button will also be less insane!

**Comment by Coirt** [comment]
Should the kill be momentary? Feel as though it should just mute the output.

Will do yeah massively changed can no longer have inverted values on buttons also `1, 0, 0`. Think I read there is an exception for `0, -1, -1` (or something)

**Comment by baconpaul** [comment]
The kill isn't a mute; the kill is rapidly and gracefully silence all the voices (basically set their attenuation to a radically high value and let them ring out). So momentary feels correct.

The exception is a one line change (`momentary = true` in button subclasses) but yeah I had to make it indeed!

I have also changed the poly output to be the "largest I need". Hold on - another push coming. Then if you could test again I would appreciate.

**Comment by Coirt** [comment]
No probs will test with sound this time :1st_place_medal:

**Comment by baconpaul** [comment]
OK give it a whirl now. Commit e70386c8dcba4215232f5287bd540a2de020c9d5 is the latest.

**Comment by Coirt** [comment]
Impressive sound out of that very nice! :smiley:

**Comment by baconpaul** [comment]
Thanks! Thanks for the fixes too; I swept them into release_v1.0.1 which should ship with Rack 1

**Comment by Coirt** [comment]
Great, no worries will let you know if anything else comes up.
