### ISSUE TITLE
Addition of BaconPlugs to Rack community repository

### ISSUE THREAD

**Issue by cschol** [baconpaul/BaconPlugs#4]
@baconpaul Do you have any objections to adding your plugin to the Rack [community repository](https://github.com/VCVRack/community)?

You can either provide a PR per the instructions int the community repository or we can do it for you.

**Comment by baconpaul** [comment]
Hi!

I've been thinking about doing this since I wrote them and haven't quite yet, mostly because I worry I don't have the bandwidth to appropriately support them as VCVRack expands.  Like: I put the pull request together, Andrew had an edit, I did the edit, then didn't pull the trigger.

For instance, the head of the code builds fun with head of rack, but I haven't done a 0.6dev binary build; I don't have a windows build environment; only have my sole mac as a test environment; etc...

I worry that a rack user may not have a professional-enough experience if my plugins are in the mix, even though I think the code is good.

That said, I rather like the plugins and may write more, so perhaps I'd turn the question around: How do you find the support load of having your plugins in the community repository, and how do you make sure people have a more-like-professional experience which I think the Rack community aims for?

Thanks so much!

**Comment by cschol** [comment]
Hi! The community support is really great. The Plugin Repair Team has been put together to help developers with API updates and provide PRs. I would not worry about it too much. There will always be people willing to help.

As far as the load goes: apart from you adding new features, people might find bugs and report feature requests. You don't HAVE to do anything and there is no time pressure either. There is wide variety of plugins in the repository. I hope to get my own plugin into the community repo before the v0.6 release. 

Your code has been built on Windows and Linux (by myself and others) and builds just fine in its current state against v0.6 of the Rack API.

Windows:

![image](https://user-images.githubusercontent.com/624427/37438772-243ad8de-27ba-11e8-8da1-1e810b6fe4e2.png)

I would put in the PR to get the plugin migrated to the `v2` repository for `v0.6` and see how it goes. Worst case, you can always ask Andrew to remove it again.

**Comment by baconpaul** [comment]
Plugin Repair Team? That sounds intriguing! 

I'm more than happy to fix my code of course. (I did the port to 0.6 one evening easily). But if there's a team which is doing things like running builds and packages for me, then almost all of my concerns go away. Is this what you all are doing?

I dream of a world where some set of servers run builds and binary releases for me into the repo from a GitHub tag. I'd gladly help support such a thing (like, pay for cycle time).

But that part of the workflow: 1: package and update the binary distro and 2:  know that my code breaks against head if I haven't built in a little would be awesome. 

If that's what you are doing that's awesome!

Even if it's not, perhaps I'll just do a 0.6 binary build for mac before I go and drop it in the repo. But can I read more about the community support?

And great that it works on windows! A few alignment problems I see but looks like the plugins.

Thanks so much!

**Comment by cschol** [comment]
See [VCV Community Invitation](https://github.com/VCVRack/community/issues/248) and [Plugin Repair Team](https://github.com/VCVRack/community/issues/269) for more information about the community support.

**Comment by baconpaul** [comment]
OK so that sounds basically exactly like the magical thing I was hoping would happen! How great!

I think the alignment problems I see in your screenshot are because of the knob size changes which posted on the API thread a couple of days ago. I'll do a pull and fix the code and push head so these plugins layout correctly against 0.6.

I'm traveling for 10 days or so starting this weekend, so won't be able to tend to the source code during that time but should be able to check it all this morning. 

But with that caveat, if your (amazingly cool and generous) team is able to do the binary packaging and json file management so on, I am more than happy to have these plugins in the community list and either modify the code as the API shifts or (if I'm away) accept and review PRs which would do that. That's so cool!

Is there a patreon or anything like that to help defray some of the build costs? Or are you all just doing it on machines under your desks?

**Comment by baconpaul** [comment]
OK so I just did a clean build against head and fixed the knob-size-change-alignment issues which came up. Everything else seems to work so I changed the VERSION to 0.6.0 from 0.6.0dev and tagged it all as v0.6.0.

Like I said, I'm away for about 10 days so won't be able to build or anything during that time, but if what I've done is enough to allow your generous community effort to get me packaged into the open distribution, happy for you to do so!

Thanks again

**Comment by cschol** [comment]
Thank you for fixing this so quickly! I will submit the plugin to the community repository.

As for Patreon-type stuff, if you want to support Andrew, buy some of his commercial VCV modules he offers. He would appreciate that. They're awesome and they support VCV development. Thank you again!

**Comment by baconpaul** [comment]
Awesome. 

And thanks again for your efforts! Honestly knowing that there's a build option for me makes it more likely for me to add those other plugins which are in my head!

My one other question: Lets say I add one of those other ideas that is in the TODO.md and have another plugin. Is the workflow to get my 0.6.1 modules deployed easy? That wasn't clear to me from the documentation you shared.

Really appreciate all the help.

**Comment by cschol** [comment]
Yeah, you (or someone else) updates the `git submodule` "manifest", i.e. the `SHA` that the submodule points to in the new community repository, submits a PR for that and as soon as it is merged, the new build rolls out. If someone else does it, they just need to know when your new version is ready. I would think, there will be additional documentation for plugin developers describing the workflow with submodules, once the repository is live.

**Comment by baconpaul** [comment]
Well that sounds wonderful. Thanks again! I'm closing this issue now, also.

Appreciate the help.
