### ISSUE TITLE
HarMoNee toggles

### ISSUE THREAD

**Issue by Whisper3000** [baconpaul/BaconPlugs#48]
Hi, I love the HarMoNee module, but I'm having trouble toggling via cv. Do the toggles take a gate? A trigger? Something else? I've been sending triggers, gates, square waves and sine waves to the cv inputs of the toggles, but nothing happens. I haven't found another harmonic module that works as well, and as easily as yours, and if I could get the toggles to work I'd like it even more.

Thanks for your help

**Comment by baconpaul** [comment]
Wow its been what 2 years since you posted this? Sorry about that

Anyway they take a gate a threshold 5v but I'm going to change it right now to a gate with threshold 2V. Here's the network I used to test it. Will close when the 2V change goes in.

<img width="800" alt="Screen Shot 2022-10-28 at 10 19 17 AM" src="https://user-images.githubusercontent.com/13387561/198640261-30b2a477-a604-46c5-a5e4-190f2aa47f0c.png">
