### ISSUE TITLE
Proposal on PolyGnome (darkroom lighting)

### ISSUE THREAD

**Issue by firolightfog** [baconpaul/BaconPlugs#55]
I have anyway a soft spot for 7-segment screens :) and I think PolyGnome does look gorgeous. 

Would you please also consider adding moderate lighting to the digits for the dark room? 

<img width="415" alt="image" src="https://user-images.githubusercontent.com/34127628/147507929-ced7064a-0f71-462f-8685-b51f2571679b.png">

**Comment by baconpaul** [comment]
i'm a bit behind on what's new in rack land. what is the dark room and how do I activate it? do you know if my plugin gets notified?

thank you for the complement on the module!

**Comment by baconpaul** [comment]
ahh bummer none of the build chain works on M1 it seems

well it will be a bit until i get to these then. Will have to grab a linux box and set up a rack build.

**Comment by firolightfog** [comment]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/34127628/147510185-6fe00c6f-2d58-4d4f-b9e6-8bf625dfab32.png">

I'm afraid I can't help with the module development point of view.

**Comment by baconpaul** [comment]
I know its been forever since you asked for this, but I've returned this fall to Rack development (look for a total reboot of the Surge modules sometime next week!) and so now am coming back and investing in / cleaning up these modules some.

Here's what will be in the next release.

<img width="600" alt="Screen Shot 2022-10-28 at 10 57 34 AM" src="https://user-images.githubusercontent.com/13387561/198663389-a5f522c3-51be-49f7-9dd0-beceb6b287d1.png">
